builds:
- id: "budget"
  binary: budget
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
checksum:
  name_template: 'checksums.txt'
dist: /tmp/budget/dist
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: alphauslabs
    name: budget
brews:
- tap:
    owner: alphauslabs
    name: homebrew-tap
  name: budget
  homepage: "https://github.com/alphauslabs/budget"
  description: "The official command line interface for Alphaus internal budget service."
  folder: Formula
  install: |
    bin.install "budget"
  test: |
    assert_match /Command line interface for /, shell_output("#{bin}/budget -h", 0)
